export const stars = [
    {
      id: 1,
      name: "Vincent Lagaffe",
      bio: "Le jet ski c'est mon dada",
      img: "https://file1.telestar.fr/var/telestar/storage/images/2015/photos/vincent-lagaf-decroche-un-record-du-monde-grace-au-flyboard-!-photos-132229/989014-1-fre-FR/Vincent-Lagaf-decroche-un-record-du-monde-grace-au-Flyboard-!-Photos.jpg?alias=original",
      publishedAt: "2020-10-10",
      isPickedByTeam: false,
    },
    {
      id: 2,
      name: "Justin Bieber",
      bio: "hahahahahcedfplêd",
      img: "https://media.gqmagazine.fr/photos/640b1aa5bd6f5c8e911df9ea/master/pass/010322_JBHair_01.jpg",
      publishedAt: "2021-10-10",
      isPickedByTeam: false,
    },
    {
        id: 3,
        name: "Britney Spears",
        bio: "aby One More Time est considéré comme le plus grand premier single de tous les temps par Rolling Stone en 2020",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Britney-Spears-Vegas-July-13-2016.jpg/330px-Britney-Spears-Vegas-July-13-2016.jpg",
        publishedAt: "2022-4-10",
        isPickedByTeam: false,
      },
    {
        id: 4,
        name: "Ryan Reynolds",
        bio: "Il commence sa carrière à l'âge de quatorze ans et se fait connaître en 1998 avec son rôle de Michael ",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_%28cropped%29.jpg/330px-Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_%28cropped%29.jpg",
        publishedAt: "2020-12-10",
        isPickedByTeam: true,
      },
    {
        id: 5,
        name: "Gary Oldman",
        bio: "Il est particulièrement célèbre pour ses rôles de méchants au cinéma, tels que Lee Harvey Oswald dans JFK (1991) d'Oliver Stone, le comte Dracula dans Dracula (1992), l'adaptation de Francis Ford Coppola",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Gary_Oldman_Cannes_2018.jpg/330px-Gary_Oldman_Cannes_2018.jpg",
        publishedAt: "2023-12-25",
        isPickedByTeam: true,
      },
    {
        id: 6,
        name: "Salma Hayek",
        bio: "Elle est révélée durant les années 1990 sous la direction de Robert Rodriguez, avec Desperado (1995), Une nuit en enfer (1996) et The Faculty (1998). ",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Salma_Hayek_by_Gage_Skidmore_2.jpg/390px-Salma_Hayek_by_Gage_Skidmore_2.jpg",
        publishedAt: "2019-12-10",
        isPickedByTeam: false,
      },
      {
        id: 7,
        name: "Antonio Banderas",
        bio: "Il est surtout connu par la critique pour ses nombreuses collaborations avec le réalisateur Pedro Almodóvar depuis les années 1980",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Antonio_Banderas_2019_%28cropped%29.jpg/390px-Antonio_Banderas_2019_%28cropped%29.jpg",
        publishedAt: "2021-8-14",
        isPickedByTeam: true,
      },
  ];


